### PR TITLE
remove warning for bs58 5.0.0

### PR DESCRIPTION
**Pull request by beeman**
When installing `@solana/wallet-adapter-react`, this message appears when you have the latest version of `bs58` installed. 

> warning "@solana/wallet-adapter-react > @solana/wallet-standard-wallet-adapter-react > @solana/wallet-standard-wallet-adapter-base@1.1.1" has incorrect peer dependency "bs58@^4.0.1".

This patch widens the dependency range.

### CODE REVIEW

**Comment by beeman** [comment]
Friendly ping, would be great if this could be merged! 🙌

**Comment by jordaaash** [comment]
Looks good! Can you add a patch changeset?

**Comment by jordaaash** [comment]
Hmm actually, I need to think about this change and see how we're using the dependency. bs58 5 breakingly changes from Buffer to Uint8Array types.

**Comment by gcangussu** [comment]
This affect us as well, the warning show up every time we install/change dependencies. I can report that we've been using this package with bs58@5.0.0 without any issues for the past months.

**Comment by beeman** [comment]
> This affect us as well, the warning show up every time we install/change dependencies. I can report that we've been using this package with bs58@5.0.0 without any issues for the past months.

Same, zero issues since the moment I created this PR.

I think we're safe here 😄

**Pull request closed without merging**
